name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fps
    
    steps:
    - uses: actions/checkout@v4

    - name: Log folder items
      run: |
          echo "Current folder items:"
          ls -al
      
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: '19.x'
     
    - name: Build
      run: |
        npm install
        npx webpack
