name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
  
    
    steps:
    - uses: actions/checkout@v4   
      
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: '19.x'
     
    - name: Build
      run: |
        cd fps
        npm install
        npm run build
        
    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: fps/dist
